### ISSUE TITLE
[Bug] 在ArchLinux下编译错误

### ISSUE THREAD

**Issue by zxp19821005** [Beadd/Creamplayer#56]
如题。
### 环境
OS：EndeavourOS
内核：6.1.39-2-lts
DE：Cinnamon
NodeJs：18.17.0
npm：9.6.7
### npm install
```
$ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@achrinza/node-ipc@9.2.2',
npm WARN EBADENGINE   required: { node: '8 || 10 || 12 || 14 || 16 || 17' },
npm WARN EBADENGINE   current: { node: 'v18.17.0', npm: '9.6.7' }
npm WARN EBADENGINE }
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated electron-osx-sign@0.5.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'

> creamplayer@0.1.0 postinstall
> electron-builder install-app-deps

  • electron-builder  version=22.14.13

added 1589 packages in 13s

2 packages are looking for funding
  run `npm fund` for details
```
### npm run build
```
$ npm run build

> creamplayer@0.1.0 build
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


 ERROR  Error: Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'
        Require stack:
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/plugin.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/index.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/config/base.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/Service.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'
Require stack:
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/plugin.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/index.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/config/base.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/Service.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js:30:31)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
```
###  npm run electron:build
```
$ npm run electron:build

> creamplayer@0.1.0 electron:build
> vue-cli-service electron:build

 INFO  Bundling render process:
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


 ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
```

**Comment by zxp19821005** [comment]
@cyh1998 谢谢！
按照so上的
### 方法1：`npm update vue-loader`
```
$ npm update vue-loader

up to date in 1s

2 packages are looking for funding
  run `npm fund` for details
```
```
$ npm run build

> creamplayer@0.1.0 build
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


 ERROR  Error: Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'
        Require stack:
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/plugin.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/index.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/config/base.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/Service.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'
Require stack:
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/plugin.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/index.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/config/base.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/Service.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js:30:31)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
```
问题依旧。
### 方法2: `npm install vue-loader@latest`
```
$ npm install vue-loader@latest


up to date in 2s

2 packages are looking for funding
  run `npm fund` for details
```
```
$ npm run build

> creamplayer@0.1.0 build
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


 ERROR  Error: Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'
        Require stack:
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/plugin.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/index.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/config/base.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/Service.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'
Require stack:
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/plugin.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/index.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/config/base.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/Service.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js:30:31)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
```
### 方法3: `npm i vue-loader`
```
$ npm i vue-loader

up to date in 1s

2 packages are looking for funding
  run `npm fund` for details
```
```
$ npm run build   

> creamplayer@0.1.0 build
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


 ERROR  Error: Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'
        Require stack:
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/plugin.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/index.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/config/base.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/Service.js
        - /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'
Require stack:
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/plugin.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/index.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/config/base.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/lib/Service.js
- /home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/tmp/Creamplayer-4.0.0/node_modules/vue-loader/dist/pluginWebpack5.js:30:31)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
```
### 方法4: `npm i webpack`
```
$ npm i webpack

added 66 packages, removed 83 packages, and changed 19 packages in 6s

2 packages are looking for funding
  run `npm fund` for details
```
```
```
$ npm run build

> creamplayer@0.1.0 build
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠏  Building for production...

 WARNING  Compiled with 2 warnings                                                                                                                                                         11:22:59

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/chunk-vendors.39c9e33a.js (246 KiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (252 KiB)
      js/chunk-vendors.39c9e33a.js
      css/app.d9d1dd1c.css
      js/app.4f355433.js


  File                                 Size                                                                         Gzipped

  dist/js/chunk-vendors.39c9e33a.js    246.27 KiB                                                                   85.75 KiB
  dist/js/732.d7946545.js              72.41 KiB                                                                    25.37 KiB
  dist/js/929.4df1ebec.js              23.48 KiB                                                                    4.44 KiB
  dist/js/831.7bc3d54c.js              6.97 KiB                                                                     2.95 KiB
  dist/js/186.172b5529.js              5.95 KiB                                                                     1.98 KiB
  dist/js/app.4f355433.js              5.84 KiB                                                                     2.70 KiB
  dist/css/929.72b1ba08.css            13.85 KiB                                                                    1.51 KiB
  dist/css/831.553ec601.css            0.86 KiB                                                                     0.39 KiB
  dist/css/186.629ac600.css            0.74 KiB                                                                     0.26 KiB
  dist/css/app.d9d1dd1c.css            0.04 KiB                                                                     0.06 KiB

  Images and other types of assets omitted.
  Build at: 2023-08-04T03:22:59.318Z - Hash: f9531a8c5ed7656b - Time: 6521ms

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
```
